
# .github/workflows/warming-agent.yml
name: Warming Agent

on:
  schedule:
    # This runs at 13:00, 16:00, and 20:00 UTC
    # which is 9am, 12pm, and 4pm EDT
    - cron: '0 13 * * *'
    - cron: '0 16 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -i -X POST "${{ secrets.https://bfsvjatcbhkxopdwzvhs.supabase.co/functions/v1/warming-agent}}" \
            -H "Authorization: Bearer ${{ secrets.0382e6ffac9fa366ae77941fbbc9e62734b8ee18d3423578ad397ec82b17fe56}}" \
            -H "Content-Type: application/json" \
            -d '{}'
